services:
  grafana:
    image: grafana/grafana:12.0.1
    ports:
      - "3000:3000"
    volumes:
      - ./etc/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./etc/grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./etc/grafana/dashboards:/etc/grafana/dashboards
      - ./data:/var/lib/grafana
      - ./etc/sqlite.db:/etc/sqlite.db
    environment:
      - GF_INSTALL_PLUGINS=frser-sqlite-datasource,grafana-googlesheets-datasource,redis-datasource,yesoreyeram-infinity-datasource
    depends_on:
      - redis

  redis:
    image: redis:7.4
    ports:
      - "6379:6379"
    volumes:
      - ./etc/dump.rdb:/data/dump.rdb

  app:
    build: ../../app/fastapi
    image: ghcr.io/blueswen/grafana-zero-to-hero/fastapi:latest
    ports:
      - "8000:8000"
    command: uv run fake_todo.py
